In [1]:
# Standar Library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Import library Scikit-Learn
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.naive_bayes import MultinomialNB

In [3]:
# Import Library Sklearn (Evaluasi Tak Bertingkat)
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# Import Library Sklearn (Evaluasi Berperingkat)
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score

In [9]:
# Import Library untuk Stemming
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

ModuleNotFoundError: No module named 'Sastrawi'

In [8]:
# Open Dataset
data = pd.read_excel('dataKumparan1.xlsx')
data.head()

,Topic,Title,Content
0,Politik,"Pelanggaran Pemilu, Tiga Caleg di Sulteng Dipr...","Komisioner Bawaslu Sigi, Sulawesi Tengah, Agus..."
1,Politik,"Pemilu Susulan di Kota Jayapura, Suara Jokowi ...",Walaupun dua dari lima distrik melakukan pemil...
2,Politik,"Tsamara Amany Dipinang, Pengurus PSI Daerah Me...","Tsamara Amany, politisi Partai Solidaritas Ind..."
3,Politik,Ada 47 TPS di Sulawesi Utara Berpotensi Pemili...,Badan Pengawas Pemilu (Bawaslu) Provinsi Sulaw...
4,Politik,Ketua KPPS di Sleman Ditemukan Tewas Gantung D...,"Tugiman, Ketua Kelompok Penyelenggara Pemungut..."

In [9]:
# Ukuran Dataset
print(f"Ukuran Dataset: {data.shape}")

Ukuran Dataset: (60, 3)

In [10]:
# Pembagian data training & testing
x_train, x_test, y_train, y_test = train_test_split(data['Content'], data['Topic'], train_size=0.5, test_size=0.16)

In [11]:
train_data = pd.DataFrame({'teks':x_train, 'label':y_train})
test_data = pd.DataFrame({'teks':x_test, 'label':y_test})

In [12]:
df1 = pd.DataFrame(train_data)
print(df1)

                                                 teks      label
13  Aplikasi dan situs ayojagatps.com ikut meramai...    Politik
36  Platform media sosial populer Instagram kembal...  Teknologi
48  Pariwisata Bintan terus menunjukan perkembanga...     Travel
54  Selain mempertimbangkan budaya, alam, dan kuli...     Travel
1   Walaupun dua dari lima distrik melakukan pemil...    Politik
14  KPU memberikan klarifikasi mengenai banyaknya ...    Politik
19  Cawapres 02 Sandiaga Uno menanggapi rencana ca...    Politik
52  Hari Bumi yang diperingati pada tanggal 22 Apr...     Travel
40  Wahana hiburan Trampolin hadir pertama kali di...     Travel
56  Sulawesi Utara (Sulut) menunjukkan komitmennya...     Travel
29  Mesin pencari Google menampilkan sebuah doodle...  Teknologi
45  Jumat (19/4) kawasan Terminal Keberangkatan Do...     Travel
18  Isu kecurangan di Pemilu 2019 terus menyeruak....    Politik
59  Di balik kemegahan Pegunungan Tianzhu China, a...     Travel
50  Untuk pertama kalinya dalam 300 tahun, Vatikan...     Travel
25  Apple ternyata tidak main-main untuk terjun ke...  Teknologi
46  Kebakaran terjadi di terminal keberangkatan do...     Travel
0   Komisioner Bawaslu Sigi, Sulawesi Tengah, Agus...    Politik
4   Tugiman, Ketua Kelompok Penyelenggara Pemungut...    Politik
32  Super hype! Penayangan perdana film 'Avengers:...  Teknologi
49  Bila biasanya mesin fotokopi terdapat di kios-...     Travel
58  Setuju atau tidak, ruang bagasi penyimpanan da...     Travel
53  Untuk mendukung pengembangan pariwisata Sulawe...     Travel
26  Sistem operasi iOS terbaru untuk perangkat App...  Teknologi
28  Masyarakat Indonesia menggunakan hak pilihnya ...  Teknologi
5   Menteri Komunikasi dan Informatika (Menkominfo...    Politik
10  Peraturan pemilu mengenai presidential thresho...    Politik
21  Facebook hari Rabu mengaku telah secara tidak ...  Teknologi
51  Tahun 2018 lalu, keluarga besar Kim Kardashian...     Travel
33  Pada awal bulan April, ada sebuah berita besar...  Teknologi

In [14]:
# test_data.head()
df2 = pd.DataFrame(test_data)
print(df2)

                                                 teks      label
15  Mantan Ketua Mahkamah Konstitusi (MK), Mahfud ...    Politik
44  Hari Guru atau Minggu Apreasi Guru di Amerika ...     Travel
30  Kemajuan teknologi memudahkan dan mengubah keb...  Teknologi
34  Persaingan aplikasi pesan instan kian sengit s...  Teknologi
55  Maskapai bersimbol singa merah, Lion Air kerap...     Travel
9   Seorang Ketua KPPS bernama Baharuddin Effendi ...    Politik
39  Perusahaan e-commerce marketplace Tokopedia ke...  Teknologi
23  Untuk memberikan pengalaman yang berbeda bagi ...  Teknologi
38  Kamu mungkin pernah merasa kesulitan untuk ber...  Teknologi
57  Kabar bahagia datang bagi para penyelam di sel...     Travel

In [15]:
# Ukuran Data Training & Testing
print(f"Ukuran data train: {train_data.shape}")
print(f"Ukuran data test: {test_data.shape}")

n_train = train_data.shape[0]
n_test = test_data.shape[0]

Ukuran data train: (30, 2)
Ukuran data test: (10, 2)

In [16]:
sparse_data = pd.concat([train_data, test_data], ignore_index=True)
sparse_data.head()
df3 = pd.DataFrame(sparse_data)
print(df3)

                                                 teks      label
0   Aplikasi dan situs ayojagatps.com ikut meramai...    Politik
1   Platform media sosial populer Instagram kembal...  Teknologi
2   Pariwisata Bintan terus menunjukan perkembanga...     Travel
3   Selain mempertimbangkan budaya, alam, dan kuli...     Travel
4   Walaupun dua dari lima distrik melakukan pemil...    Politik
5   KPU memberikan klarifikasi mengenai banyaknya ...    Politik
6   Cawapres 02 Sandiaga Uno menanggapi rencana ca...    Politik
7   Hari Bumi yang diperingati pada tanggal 22 Apr...     Travel
8   Wahana hiburan Trampolin hadir pertama kali di...     Travel
9   Sulawesi Utara (Sulut) menunjukkan komitmennya...     Travel
10  Mesin pencari Google menampilkan sebuah doodle...  Teknologi
11  Jumat (19/4) kawasan Terminal Keberangkatan Do...     Travel
12  Isu kecurangan di Pemilu 2019 terus menyeruak....    Politik
13  Di balik kemegahan Pegunungan Tianzhu China, a...     Travel
14  Untuk pertama kalinya dalam 300 tahun, Vatikan...     Travel
15  Apple ternyata tidak main-main untuk terjun ke...  Teknologi
16  Kebakaran terjadi di terminal keberangkatan do...     Travel
17  Komisioner Bawaslu Sigi, Sulawesi Tengah, Agus...    Politik
18  Tugiman, Ketua Kelompok Penyelenggara Pemungut...    Politik
19  Super hype! Penayangan perdana film 'Avengers:...  Teknologi
20  Bila biasanya mesin fotokopi terdapat di kios-...     Travel
21  Setuju atau tidak, ruang bagasi penyimpanan da...     Travel
22  Untuk mendukung pengembangan pariwisata Sulawe...     Travel
23  Sistem operasi iOS terbaru untuk perangkat App...  Teknologi
24  Masyarakat Indonesia menggunakan hak pilihnya ...  Teknologi
25  Menteri Komunikasi dan Informatika (Menkominfo...    Politik
26  Peraturan pemilu mengenai presidential thresho...    Politik
27  Facebook hari Rabu mengaku telah secara tidak ...  Teknologi
28  Tahun 2018 lalu, keluarga besar Kim Kardashian...     Travel
29  Pada awal bulan April, ada sebuah berita besar...  Teknologi
30  Mantan Ketua Mahkamah Konstitusi (MK), Mahfud ...    Politik
31  Hari Guru atau Minggu Apreasi Guru di Amerika ...     Travel
32  Kemajuan teknologi memudahkan dan mengubah keb...  Teknologi
33  Persaingan aplikasi pesan instan kian sengit s...  Teknologi
34  Maskapai bersimbol singa merah, Lion Air kerap...     Travel
35  Seorang Ketua KPPS bernama Baharuddin Effendi ...    Politik
36  Perusahaan e-commerce marketplace Tokopedia ke...  Teknologi
37  Untuk memberikan pengalaman yang berbeda bagi ...  Teknologi
38  Kamu mungkin pernah merasa kesulitan untuk ber...  Teknologi
39  Kabar bahagia datang bagi para penyelam di sel...     Travel

In [17]:
# Ukuran Sparse Data
print(f"Ukuran sparse data: {sparse_data.shape}")
n_document = sparse_data.shape[0]

Ukuran sparse data: (40, 2)

## Buat daftar stop word dari data yang terdapat dalam file Excel yang telah disediakan.

In [36]:
# Create a stop word list from the Excel data
stop_words = set()
for index, row in data.iterrows():
  if isinstance(row['Content'], str):
    words = row['Content'].lower().split()
    for word in words:
      stop_words.add(word)

print("Stop word list:", stop_words)

Stop word list: {'kunjungi,', 'gugur,', 'rudiantara.', 'menampilkan', 'budaya,', 'tabayun', 'aziz', 'mei.', 'ngurah', 'penggemarnya', 'ditutup', 'petualangan,', 'dekat', 'sudarno', 'mengubah', 'nah', 'aparat', 'diembannya.', 'surat', '“ada', 'kelaikudaraan', 'komisinya', 'swipe', 'dilaksanakan.', 'berbeda,', 'berjam-jam.', 'laguna', 'ditarik', 'informasi.', 'maret,', 'jam,', 'mewakili', 'mengalihkan', 'per', 'bikin', '1958.', '"ya', 'unggu', '94', 'salib', 'sandi.', 'setuju,', 'setiap', 'river.', 'melanjutkan', 'kian', 'peserta', 'terbaru', 'ayam,', 'timur,', 'merekam', 'dulu', 'redaksi', 'pemberian', 'fisik', 'usai.', 'superman', 'instansi:', 'tercapai,', 'guru', 'noda,', 'lurah,', 'komitmen', 'masukkan', 'beyond', 'bali.', 'menit.', 'djoko', 'penjumlahan', 'potensial', 'surga', 'diadakan', 'ktp', 'rekayasa', 'saifudin,', 'andy.', 'permasalahan', 'besoknya', '“apa', 'berminat', 'mengakui', 'smartphone', 'abad', 'eiffel.', 'temuan', 'segera', 'asdep', '6s,', 'bolmunt', '(24/4)', 'dpr', 'diperingati', 'hitung', 'sapta', 'sancta.', '1997', 'dang', 'optimasi', 'meliput.', 'dewan', 'muhammadiyah', 'konsultan', 'manfaatnya,', 'kira-kira', 'impossible', 'berlomba-lomba', 'melestarikan', '(hand', 'pantauan', 'jess', '(artificial', '44,16', 'bawah,', 'pencarian', 'direkam,', 'terpesona', 'internasional.', 'mantan', 'ucapan', 'menemukan', 'pengguna.', 'dipilih', 'kumpulkan', 'tersebut,', 'sana,', 'situng', 'rantai', 'konser', 'for', 'robianto,', 'review', 'reality', 'peternakan,', 'alokasi', 'dulu,', 'masif,"', 'mit', 'ekonomi,', 'integrated', 'diklik,', 'maka,', 'perkiraan', 'permukaan', 'nampan', '10%', 'bela', 'ngajar', 'berat', 'madya,', 'yesus', 'biaya', '2', 'humas', 'konsumen.', 'headset,', 'noc', 'pihak,', 'dilakukan', 'niaga', 'kota-kota', 'bandar', 'jadwal', 'bioskop', 'rai', 'staf', 'pontianak', 'dia', 'para', 'kojo,', 'resmi,', '7.200', 'berhentinya', 'dirasa', 'totalnya', 'keluarganya', 'nu,”', 'kandungan', 'berapa', 'wonderful', 'spot', 'miahasa', 'ungkapnya.', 'serangan', 'capek', '(tps),', 'jerami', 'sebelumnya.', 'layanan', 'malta,', 'macan', 'keluarga,', 'dirusak', 'lukas', 'lancar.', 'perjuangannya', 'rendah', 'it', 'membatasi.', 'jajaran', 'politisi', 'sosial,', 'meriah.', '1', 'petunjuk', 'mencapai', 'terancam,', 'kiri', '"di', 'ventilasi', 'dapur', 'mana', 'diminta', 'anggap', 'pula,', 'polin,', 'regional', 'teks', 'dibawa', 'penegak', 'terbesar', '(ar).', 'cagar', 'jumlah', 'hal', 'kedua,', 'camping', 'sungai,"', 'musik.', '25', 'buku', 'penyelesaian', 'haji,"', 'terganggu', 'nyaman', 'terhenti', 'cynthia', 'layarnya.', 'role', 'malang.', 'publik', 'dan', 'airport,', '56', 'kampung', 'ujarnya', 'keselamatan', '"kami', 'lega.', 'sosial', 'kontroversi', 'tethering.', 'tiap', 'coral', 'satu-satunya', 'menjanjikan', 'sebisa', 'raksasa', '(psu).', 'ungkap', '80', 'menghilangkan', 'peringkat', 'referensi', 'perannya,', 'sekolah,”', 'suara,', 'mereka', 'daya', '(pks)', 'nasihat-nasihat,', 't2s,', 'utara,', 'berkelahi', '(atraksi,amenitas,', 'alhasil,', 'tim', 'keras.', 'satsiun', 'tenda', 'sejarahnya', 'kong', 'sendiri,"', 'sedangkan,', 'virtual', 'enggan', 'bpn,', 'harga', '“(tugiman)', 'peace', 'penelitian', 'arsitek', 'antisipasi', '(arrival)', 'hadapan', 'mengaplikasikan', 'count,', 'meminta', 'fitri.', 'menggulirkan', 'layanan-layanannya', '22', 'siswono.', 'datar.', 'ploso', 'daring', 'diberlakukan', 'menjawab,”', 'australia,', 'mp,', 'solidaritas', 'tergantung', 'ricis,', 'jelasnya.', 'menyelesaikan', 'dihuni', 'satu', 'tps-tps', 'memindahkan', '82,78', 'reuters', 'tersedia', 'sula', 'berukuran', 'perilaku', '50', 'mengalirkannya', '3', 'pencoblosan', 'ini.', 'dimandikan.', '"kota', 'keluarga.', 'disiplin', '(if)', '(load', 'itu', 'main-main', 'idealisme', '(on', 'menit', 'pas', '2005.', '(direktorat', 'kapolsek', 'thomas', 'bertugas.', '17', 'merilis', 'laura,', 'makan', 'kekhawatiran,', 'duka,', '02', 'pembina', 'beach4teach', 'brisbane,', '"ini', 'khususnya', 'masyarakat.', 'pertiga', 'dia.', 'berkompetisi', 'ditambah,', 'noken.', 'menurun,', 'berpose', '“yang', 'kekmampuan', 'mahfud,', 'emisi', 'berkunjung', 'tetapi,', 'road', '(real', 'kehadirannya.', 'wealth', 'bertemakan', 'tab', 'silam.', 'tumbuh', 'ekor', 'lanjut', 'djazuli,', 'ar/vr', '400-420', 'develop', 'penundaan', 'manager', 'kebagian', 'siang', 'digelar', 'globaldi', 'antrean', '2019-2024.', 'mengklaim', 'terlihat', 'demikian,', 'ditemui', 'perbedaannya', 'seizinnya', 'rentang', 'pasok', 'pembuatan', 'suara"', '546', 'pileg', 'manual', '79', 'pandangan', 'pesantren', 'pihaknnya', 'bpn', 'content', 'operasional', 'pemimpin,', 'terutama', 'daerah', 'tajam', 'k,', 'terkait.', 'boga)', 'konfigurasi', 'prabowo.', 'tps', 'bukti', 'satuan', 'translator', 'bandara,', 'karena', 'berawal', 'terletak', 'pribadi', 'brand', 'format', 'istirahat,', 'time', 'kelompok', 'anggota.', 'trafik', 'toko', 'bersantai.', 'c1.', 'millennials', 'legislatif', 'tapi,', 'sebab', 'tv,', 'situ', 'khloe', 'bertolak', 'dimasukkan', 'berikan', 'avengers', '“terus', 'lapangan', '38,', 'banget', 'sampingnya', 'duo', 'kini,', 'pasta', 'hasil', 'rizki', '53', 'cadangan', 'disampaikan', 'kebakaran', 'arena', 'bertinta', '800', 'mudah.', 'ngajar,', 'lanjut,', 'mempersilakan', 'utara', 'menewaskan', 'mekanik.', 'wahananya,', 'asingnya.', 'umum', 'terindah', 'stories.', 'kecamata', 'dong', 'pariwisatanya', 'tanda', 'mencerminkan', 'suku', 'basket,', 'meksiko.', 'ar,', 'vim,', 'memperlihatkan', 'nyawa,', 'permasalahannya.', 'tourism.', 'pengelolaan', 'terdiri', 'menteng,', 'pemantau', 'pilihnya', 'dimenangkan', 'otomatisasi', 'balutan', 'kecil', 'memperkenalkan', 'diramaikan', 'merekap', 'tukasnya.', 'al-furqan', 'setidaknya', 'bermanfaat', 'insider.', 'kebijakan', 'ikat,', 'kekinian', 'usia', '(coe', 'china', 'terbaik', 'mengembangbiakkan', 'masyarakat', 'tentunya', 'sapi,', 'mobil,', 'pontianak.', 'berkata,', 'masing-masing,', 'bumi,', '(data', 'kalangan', 'delta', 'penundaan.', 'bantu', 'kpu', 'if', 'menakjubkan', 'tegasnya.', 'pemeliharaan', 'faktor,', 'pkb', 'membantu', 'aman', 'juruselamat.', 'dari', 'kamal', 'pendownload', 'si', 'bisnis', 'penduduk', 'menyinggung', 'musda', 'seiring', 'menawarkan', 'aksesibilitas', 'makanan.', 'louis,', 'kerja,', 'interactive,', 'mengunjungi', 'jepang', 'aksesibilitas)', 'pesona', 'dimensi,', 'manado', 'riset', 'as', '(personal', 'keberangkatan.', 'pelopor', 'kpps', '"duka', 'wartawan', 'memang', 'lainnya,', '(muntah-muntah),', 'memudahkan', 'malaysia,', "'berisi'", 'alibaba', 'potensi', 'pdip,', 'buatan', '“saya', 'bayi/bahan', 'suci', 'berwarna', 'technology', 'sampai', 'pilihan', 'dilaksanakan', '26-29', 'dulunya', 'lihat', 'berharap', 'menyusun', 'daily', '“tadi,', 'amazon.', 'kolaborasi', 'gaya', 'lainnya', 'purnama.', 'ditawarkan', 'sungai', 'terkadang,', 'charging', 'canggih', 'garda', 'disiksa', 'sergey', 'diantaranya', 'tragedi', 'barat,', 'kecerdasan', 'menempati', 'wahyu.', 'masuk),', 'padat', 'menyarankan,', 'perhubungan', 'simpel”,', 'titik', 'konsumen', 'soekarno.', 'angka', 'seni', 'meter,"', 'ya', 'orang.”dalam', 'kayu,"', 'of', 'do', '(situng)', 'sancta,', 'tewas', 'rutin', 'menilai,', 'anwar', 'dicky.', 'dapatkan', 'prabowo', 'gang', 'survei,', 'semacam', 'kejadian,"', 'leisure.', 'kanan', 'saji', 'jakarta', 'emoji', 'kasihan', 'prosentase', 'sengit', 'berdiri', 'star,', 'dicoblos', '&', 'syarat.', 'memberinya', 'goreng,', 'riau', 'jokowi-ma’ruf,”', 'kelurahan', 'lima', 'oppo,', 'mengapresiasi', 'mungkin', 'bebas', 'rumit.', 'ditutup.', 'menganiaya', 'ramai', '“akibat', 'pendataab', 'pengelola', 'memori', 'pentingnya', 'kios-kios', 'ribu.', '15.00', 'banjir', '"tak', 'bintan', 'kesehatan', 'sehingga', 'secrets,', 'lingkungan,', 'memencet', "'avengers:", 'diulang,', 'buas.', 'c1', '2017', 'pesta', 'beri', 'merak,', 'design', 'pura', 'paket', 'utama,', 'situasi', 'memberi', 'panoramic', 'unggul', 'diartikan', 'dimasukkan,', 'ratna', '40', 'berkumpulnya', 'dibandingan', '(departure)', 'penumpangnya', '11,12%.', 'bonjol,', 'ditetapkan', '(55%)', 'ton', 'terhitung', 'lalu', 'message', 'potocopy', 'pajak,', 'anggur', 'rencana', 'bisnis,', 'bunaken,', 'portal,', 'developer', 'menghapusnya,”', 'peningkatan.', '64', 'nantinya', 'spesifikasi', 'destinasi', 'saking', 'menanti', 'threshold', 'ketika', '45', 'besar', 'senayan', 'penginapan', '4', 'terburu-buru.', 'byme.', '50.000,', 'sistem', 'forum', 'membahayakan', 'gres,', 'terakhir,', 'memberitahu', 'susulan', 'berjalan,"', 'bagaimanapun', 'kuota,', 'resor,', 'secangkir', 'ikut', 'kontaknya', 'penyuka', 'diseruput', 'diakui', 'tps-nya,', 'gurame,', 'akbar', 'sedikit', 'tuan', 'credit', '1.835', 'rotasi', 'vp', 'perhatian.', 'ndalem', '"beliau', 'disediakan', '20.00', 'gambar', 'peneliti', 'manajemen', 'mulai', 'modern’', 'personalization', 'memenangkan', '1:2.500', "kardashian'", 'tercetus', 'muka,', 'membaca', 'coast', 'presiden.', '2.', 'parking', 'lebih', 'kursi', 'puluhan', 'swedia,', 'tokopedia.', 'bertemu', 'masuk', 'nusantara', 'force', 'amazon,', 'aluminium', 'runway,', 'alonissos,', 'membayar', 'influencer,', 'apa?', '"yang', 'innocent', 'izinnya', 'prioritas', 'perserikatan', 'data.', 'airasia', '"cara', 'left', 'pusing', 'canggih,', 'asal', 'muhammad,', 'pungkasnya.', 'psi,”', 'meramaikan', 'menyajikan', '7.414.564', 'kesepakatan', 'ukuran', 'diturunkan', 'dikenal', 'blue', '15.46', 'fotokopi', 'ipad', 'layanan,', 'sini.', 'keyakinan,', 'group', 'sekitarnya.', 'politik', 'istilah', 'kiai', 'air,', 'katolik', 'meninggalkan', 'pesawat)', 'mengantisipasi', 'twitter-nya', 'minggu', 'saudaranya', 'dipugar', 'penumpang', 'personalisasi', '(its),', 'berjenjang', 'dibuang.', 'bukanlah', 'siapa', 'tugasnya.', 'tugas', 'keranda', 'pro,', 'control', 'terminal', 'memverifikasinya', 'freemantle,', 'versi', 'digitalnya', 'iresearch', 'mencoblos,', 'dunia', 'sore', 'nu', 'sipil', 'pangsa', 'biasa', 'mandarin', '(fear', 'scala', '20×9', 'kelebihan', 'mengusung', 'pasar', 'oreo,', 'berbakat', 'gayanya', '38', 'semuanya', 'banjarmasin.', 'arya', 'terdekat', 'jari', 'pkb,', 'dibuat', 'terharu.', 'batal', 'teknik-teknik', 'orang.', 'kopi', 'tahap', 'dipergunakan', 'bersama', 'tahapan', 'utama.', 'april,', 'kuningan,', 'lalu,', 'mengandung', 'figure', 'berjalan', 'terbentuk,', 'burger,', 'pemprov', 'carai', 'mengonsumsi', 'berusia', 'mendukung', 'pengembang', '212.,', 'kalian.', 'kinerja', 'sempat', "'keeping", 'menentukan', '"dengan', 'herwyn', 'mantrijeron,', 'menciptakan', 'out,”', 'membentuk', 'unggahannya', '300', 'sulut?', '128', 'langsung.', 'gimana', 'perjalanan', 'operasional,', 'stasiun', '100%.', 'dibuka', 'yunani,', 'ruangan', '01.00,', 'keren.', '(yang', '2004', 'kanada.', 'apresiasi', 'habib', 'mempertimbangkan', 'dimiliki', 'ahli', 'pengasuh', 'merah,', 'ganda', 'ketua', '(kpu)', 'helena.', 'kolesterol', 'wisatawan.', 'pupr', 'gandum.', 'layanannya', 'grassroot,', 'terasa', 'penjual', 'kapan', 'mengingat', 'darussalam.', 'menandai', 'men-scan', 'sekali.', 'portalnya,', 'fikser,', 'indonesia,', 'senada', 'marvel.', 'saja.', 'dibagikan', 'berlangganan.', 'katanya.', 'pekerjaan', 'fast', 'penumpang.', 'niatnya', 'raya', 'nanti', 'aksesnya', 'kewajaran', '2017).', 'posisi', 'menerjemahkannya', 'suami', 'pemberitahuan', 'saat', 'malangan.', 'disumbang', 'eddy', 'laut,', 'diterbitkan', 'menuturkan', 'resort,', 'dilansir', 'keindahan', 'provinsi', 'keunggulan', 'jadi,', 'kesehatannya.', 'call', 'hong', 'hanif', 'kh', '"malam', 'damai.', 'alam,', 'sailing', 'enembe', 'rotterdam', 'sayangnya,', 'perkembangan', 'kabag', 'diverifikasi', 'penindakan', 'merangkum', 'kristus', 'dpthp', '(23/4)', 'rekayasa,"', 'tidak', 'tiketnya', 'anak-anak', 'nawawi', 'jadi', 'florikultura.', 'maeslantkering', 'menjadwalkan', 'sebut', 'ceo', 'menginformasikan', 'mengumumkan', 'silat', '"diimbau', 'kemudian,', 'lokal', 'membuka', 'masyarakat,', 'akan', 'minta', 'memadai.', '150', 'diterapkan', 'm1.', 'situs', 'nusantara,', 'karakter', 'khawatir', 'kapel', 'total', 'menyetorkan', 'ilmu', 'teliti', 'lihat.', 'dibikin', 'penutupan', 'tenang', 'begini.', 'bengkel', 'marmer', 'sekitar', '“setelah', 'mpr', 'terjual.', 'tawar', 'lulusan', 'lipat', 'jaga,', 'depan', 'line', 'ojek', 'tirai', 'penyusunan', 'ketimbang', 'suaramu.', 'jajal', 'dialokasikan', '“buat', 'digitalnya.”ada', 'merantau,', 'top', 'dugaan', 'kemarin,', 'ka-shing', 'kiai-kiai', 'ujarnya.', 'gakkumdu.', 'sawo,', 'lagu', 'maskapai', 'rabu', 'ungkapnya', '212,"', 'yunani', 'penayangan', 'kelima', 'menghemat', '800an', 'berdua', 'tepuk', 'mengawasi', 'diterima).', 'voila,', 'berkesempatan', 'depannya,', 'normal.', 'singapura.', 'adab', 'hari,”', 'tutul.', 'dorong', 'kalian', 'bahagia', 'padang,', 'sajakah', 'hoaks', 't22', 'utara.', 'captain', 'umumnya.', 'pencinta', 'pembawa', 'didanai', 'potongan', 'relatif', '(mk)', '(schedule', 'tangani', 'pbnu', 'persoalan', 'biota', 'demokrasi', 'undangan', 'apa-apa', 'yabansai,', 'masalah', 'raja', 'menerima', 'pilih', 'berkembang', 'masalahnya.', 'berusaha', 'terbenam', 'terpecah', 'bagasi', 'migration', 'sendirinya', 'lte', '"saat', 'massa', '"jangan', 'perhitungan,"', 'keterampilan', 'berbondong-bondong', 'pun,', 'film', 'kesiapan', '"kpu', 'bangkai', 'terjangkau."', 'aja', 'laki-laki', 'gak', 'disebut-sebut', 'tradisional', 'dessert.', 'diinginkan', 'ruangan.', '2019', 'pemungutan', 'ribu,"', 'malam.', 'menahan', 'rekomendasi', 'buana', '29', 'kini.', 'jayapura,', 'backend', 'facebook.', 'generasi', 'dinonaktifkan', 'kehadiran', 'korban', 'sebenarnya,', 'pemanas', 'kuantitas', 'unsur', 'kendati', 'pergerakan', 'agar', 'produknya', 'kompetitor,', 'pertemuan', 'dikasih', 'bertahan', 'lantas', '58', 'penanganan', 'asia', 'disajikan', 'monitoring', 'pemantauan', '(safety', '600.', 'heram,', 'dibahas', 'menyangka', 'perasaan', 'tepatnya', 'menghadirkan', 'merek,', 'level', 'alat-alat', 'menebus', '400', 'menunda', 'berbekal', 'messaging', '2020.', 'kotak', 'mempertahankannya,”', 'cemilan', 'translator.', 'itu,', 'ucapanmu', 'diterjemahkan.', 'mancanegara', 'sanctorum.', 'uji', 'modal', 'sementara,', 'berbagai', 'icon,', 'memimpin', 'hidup,', 'tetap', 'duo,', 'kabar', '893.400', '35.218', 'sp,', 'signifikan', 'berhak', "unlimited',", 'roma', 'menyebut', 'kematian', '(mui).', 'miliar.', 'perbudakan,', 'sam', 'arahan', 'iskandar', 'naik.', 'kamera', 'sari,', 'busa.', 'alhamdulillah', 'kenyamanan', 'daur', '(23/4).', 'menyatakan,', 'kejahatan.', 'dikarenakan', 'sudirohusodo,', '18', 'yahya', 'menyertakan', 'peningkatan', 'manshur', 'kaum', 'proses-proses', 'men-charging', 'sediakan', 'hotspot', 'sulit,', 'genpi,', 'kepolisian.', 'pemesanan', '550', 'b2b', 'masing-masing.', 'didapat.', 'kapannya', 'rapat', 'lion', 'mesin', 'arief', 'ekonomi', 'tahukah', 'terkaya', 'kali.', 'kontributor', 'populer', 'gurauan', 'diterbangkan,', 'tambaksari,', '630', 'waktu.', '(irregularities).', 'acara.', 'perusahaan', 'sesuatu,', '"hal', 'punya.', 'menyebutnya', 'dibuka.', 'adu', 'dessy,', 'launching', 'berapa,”', '‘avengers’', 'skala', 'kawalpemilu', 'tertangani', 'langsung', 'kemungkinan,', 'bandingkan', 'simpel,', 'terjun', 'tugiman', 'rumahnya', 'sambil', 'hijau', '2,', 'menenangkan', 'diri.', 'ramah', '87', 'perjalanannya', 'angkanya', 'digiring', '191.650', 'dilaporkan', 'ekonomis', 'memanaskan', 'pasca', 'sebagai', 'memakan', 'tanggapan', 'didapuk', 'airasia.', 'mencobanya', 'pendukung', 'kami', 'kelancaran', 'terbuat', 'modem', 'dessy', 'dibukanya', 'polling,', 'pengaturan', 'diketahui,', 'kawasan', 'pks,', 'informasi', 'sosial.', 'tahun.', 'seksi', 'alasan', 'pemberitaan', 'noken', 'kuis', 'kuliner,', 'kpu,"', 'terbaring', 'bermusyawarah', 'jogja', 'belaka,', 'kebiasaan', 'kebebasan', 'diong,', 'april,"', 'boarding', 'biji-bijian', 'jas', 'tagar', 'lama', 'atraksinya', 'schmidt.', 'south', 'kg', 'badai', 'apple', 'sampingan', 'linmas', 'terakhir.', 'memar', 'idul', 'tampak', 'mendapatkannya.', 'tahun,', 'hormatilah.', 'siri', 'semua,”', 'penjarahan.', 'baru', 'sekadar', 'pemerkosaan,', '(sulut),', 'bisnisnya', 'tadi', 'diri', 'berlaku', 'mengendalikan', '(quick', 'muda,', 'diminati,', 'lsm', 'bawaslu', 'juli', '19.562.', 'bagian-bagian', 'girl.', 'sulsel', 'kolam', 'memerangi', '(hingga)', 'sudah', 'communication', 'keterbatasan.', 'engineer', '“kita', 'masing-masing', 'rasa', 'lintas', 'machine', 'soewandi', 'menjelajah', 'taxiway,', 'hp.', 'terjadi', 'penawaran', 'menang', '34', 'adalah', 'koran', 'lisan', 'bagus,”', '.', 'technology,', 'platform', 'business)', 'memasukan', 'bakal', 'membumi.', 'boleh', 'bawaan', 'pagu', '"untuk', 'bahan', 'dunia.', 'update', 'india.', 'isu', 'ded', 'rudiantara', 'diberitahu.', '09:00', '(pat)', 'diterjemahkan', 'sektor', 'tombol', 'keseriusan', 'tidak,', 'di-scan', 'caleg.', 'tegas', 'pak', 'produksi', 'roadshow', 'caranya.', 'sampel', '“adapun', 'segi', 'kardus', 'atar', 'meredam', 'pusat', 'tergesa-gesa,', 'selatan,', 'hemoglobin', 'nurul', 'kontak', 'world', "ma'ruf", '“the', 'imbuhnya.', 'cerdas.', 'ios', 'gerindra', 'menghitung', 'dihadapkan', 'keterisian', 'will', 'smartfren', 'memadai,', 'lirboyo', 'cepat', 'potensial,"', 'utama', 'mengevakuasi', 'istri', '(pkb),', 'independen,', 'apreasi', 'ipb,', 'tempat-tempat', 'perumahan', 'disbudpar', 'jd.com', 'tribe', 'satukan,', 'sumber', 'offline', 'paslon', 'oppo', 'davao', 'cocok', 'perusahaan-perusahaan', 'mudah,', 'presentase', 'disebar', 'seasons', 'bungkus', 'memantau', 'senantiasa', 'psu?', 'lantaran', 'tangga', 'perlu', '5,3', 'kader', 'zoetry,', 'dkppu', 'suka', 'pemilih,', 'amazon.com', 'flight', 'game-game', 'usut,', 'liburan,', 'sigi', 'syukuran', 'komisioner', 'akbar.', 'diri,”', 'bertambah.', 'menurutnya,', 'sini,', 'tudingan', 'diberitakan', 'itulah', 'emosional.', 'menyebarkan', 'pegunungan', 'mengurangi', 'seru,”', 'juta,', 'university', 'swedia.', 'senilai', 'berpendapat,', 'sendiri,', 'vennya,', 'pagi', 'kentang', 'amany', 'dipromosikan.', 'bogor.', 'nusantara,"', 'heme', 'sm', 'bicara', 'kpu,', 'telah', 'diperbolehkan', 'senin', 'pembuat', 'teman-teman', '(94.63%', 'berkarier', 'kemenkeu', 'sambung', 'sandiaga', 'global', 'enggak', 'akhyar,', 'internasional', 'merevisi', 'pungkas', 'membahas', '(coattail', 'berada', 'berpartisipasi', 'kecewa', 'pergi', 'daging', 'mengajak', '"', '5.000', 'kebenarannya', 'brand.', 'dilarang', 'dibenamkan', 'teluk', '13.00', 'bedanya.', 'menghindari', 'pesawat', 'diliput', 'perbaikan', 'terdekat.', 'betapa', 'gianyar.', 'lawan', 'banyuwangi,"', 'milliar', 'bekerja', '(23/4),', 'korea,', 'salad', '7-12', 'patroli', 'diseret', 'sources,', 'dirasakan', 'rame', 'penyajian', 'informatika', 'datanya,"', 'screen', 'membutuhkan', 'diadopsi', 'mengumpulkan', 'berkejujuran', 'resort.', 'rentan', 'bapak', 'menimbulkan', 'lazim', 'mempublikasikan', 'ulang', 'persen.', 'sejalan', 'besar,', 'konsep', 'sih', 'benar', 'sore,', 'disamakan', '"sampai', 'indah', 'diambil', '247.579', 'tinggal', 'bergulir.', 'keinginan', 'xbox', 'kecepatan', 'cruise', 'lonjakan', 'lawas', 'menimpa', 'nagari', 'menghampiri', 'disukai.', 'pinnacles,', 'sengaja', 'helio', 'mengoreksi', 'entri', 'terunggah.', 'tahu,”', 'kebutuhan', 'daniel', 'by).', 'bertindak', '250', 'mengoptimalkan', '–ma’ruf', 'berkualitas', 'menaruh', 'cnbc.', 'dampaknya', 'sepertinya', 'publik.', 'potensial.', 'mengedepankan', 'memiliki', 'mengawal', 'selain', 'biru.', 'lahan', 'disukainya', 'masyarakat,”', 'musik', 'meningkat.', 'bawah.', 'bentuk', 'tingkat', 'setahun,', 'dimodifikasi', 'heran', '95', 'wakil', 'kepala,”', 'ya.', 'jaga', 'assistant,', 'interaksi', 'tampilkan', 'now,', 'wi)', 'pemilik', 'doa', 'layak', 'berubah,"', 'penyelam', '(bertemu),', 'rencananya', 'imbuh', 'datang.', 'ciptaannya', 'daging.', 'sarumpaet,', 'kuota', 'action),', 'tugasnya', 'klaim', '(kpps)', 'misalnya', 'chief', 'diperbaiki,', 'diharapkan', 'panas', 'menyebabkan', 'berpacu', 'laura.', 'menyediakan', 'menghadapi', 'sepuluh', 'inilah', 'menunggu', 'arcade.', 'rp', 'mencium', 'menyimpan', 'pintunya', 'gas', 'pria', 'pesawat,', 'terkena', 'penyebab', 'kerusakan', '(filipina)', 'cuma', '813.350.', 'dilewati', 'cerita', 'telekomunikasi', 'melengkapi', 'terintegrasi.',

## Skenario 2 - Tanpa Stemming Tanpa StopWord

## Skenario 3 - Dengan Stemming dengan StopWord

**Stemming**

In [21]:
# Create stemmer
stemmerFactory = StemmerFactory()
stemmer = stemmerFactory.create_stemmer()

# Stem Process
for row in range(n_document):
    sparse_data.loc[row, 'teks'] = stemmer.stem(sparse_data.loc[row, 'teks'])

In [22]:
df4 = pd.DataFrame(sparse_data)
print(df4)

                                                 teks      label
0   aplikasi dan situs ayojagatps com ikut ramai h...    Politik
1   platform media sosial populer instagram kembal...  Teknologi
2   pariwisata bintan terus tunjuk kembang yang po...     Travel
3   selain timbang budaya alam dan kuliner pasu fa...     Travel
4   walaupun dua dari lima distrik laku pilih umum...    Politik
5   kpu beri klarifikasi kena banyak temu salah in...    Politik
6   cawapres 02 sandiaga uno tanggap rencana cawap...    Politik
7   hari bumi yang ingat pada tanggal 22 april bua...     Travel
8   wahana hibur trampolin hadir pertama kali di k...     Travel
9   sulawesi utara sulut tunjuk komitmen untuk kem...     Travel
10  mesin cari google tampil buah doodle atau gamb...  Teknologi
11  jumat 19 4 kawasan terminal berangkat domestik...     Travel
12  isu curang di milu 2019 terus seruak dua timse...    Politik
13  di balik megah gunung tianzhu china ada buah d...     Travel
14  untuk pertama kali dalam 300 tahun vatikan aka...     Travel
15  apple nyata tidak main untuk terjun ke industr...  Teknologi
16  bakar jadi di terminal berangkat domestik band...     Travel
17  komisioner bawaslu sigi sulawesi tengah agus s...    Politik
18  tugiman ketua kelompok selenggara mungut suara...    Politik
19  super hype tayang perdana film avengers endgam...  Teknologi
20  bila biasa mesin fotokopi dapat di kios yang t...     Travel
21  Setuju atau tidak, ruang bagasi penyimpanan da...     Travel
22  Untuk mendukung pengembangan pariwisata Sulawe...     Travel
23  Sistem operasi iOS terbaru untuk perangkat App...  Teknologi
24  Masyarakat Indonesia menggunakan hak pilihnya ...  Teknologi
25  Menteri Komunikasi dan Informatika (Menkominfo...    Politik
26  Peraturan pemilu mengenai presidential thresho...    Politik
27  Facebook hari Rabu mengaku telah secara tidak ...  Teknologi
28  Tahun 2018 lalu, keluarga besar Kim Kardashian...     Travel
29  Pada awal bulan April, ada sebuah berita besar...  Teknologi
30  Mantan Ketua Mahkamah Konstitusi (MK), Mahfud ...    Politik
31  Hari Guru atau Minggu Apreasi Guru di Amerika ...     Travel
32  Kemajuan teknologi memudahkan dan mengubah keb...  Teknologi
33  Persaingan aplikasi pesan instan kian sengit s...  Teknologi
34  Maskapai bersimbol singa merah, Lion Air kerap...     Travel
35  Seorang Ketua KPPS bernama Baharuddin Effendi ...    Politik
36  Perusahaan e-commerce marketplace Tokopedia ke...  Teknologi
37  Untuk memberikan pengalaman yang berbeda bagi ...  Teknologi
38  Kamu mungkin pernah merasa kesulitan untuk ber...  Teknologi
39  Kabar bahagia datang bagi para penyelam di sel...     Travel

In [23]:
vectorizer = CountVectorizer()
tf = vectorizer.fit_transform(sparse_data['teks'])

print(f"Jumlah dokumen: {tf.shape[0]}")
print(f"Jumlah term: {tf.shape[1]}")

Jumlah dokumen: 40
Jumlah term: 3005

In [24]:
print("Daftar Term:")
vectorizer.get_feature_names_out()

Daftar Term:

array(['00', '000', '0004', ..., 'zat', 'ziarah', 'zoetry'], dtype=object)

In [27]:
print("Daftar Stopword")
vectorizer.get_stop_words()

Daftar Stopword

In [30]:
print("Matriks Tf:")
tf_matrix = pd.DataFrame(tf.toarray(), columns=vectorizer.get_feature_names_out()) # Corrected keyword argument to 'columns'
tf_matrix

Matriks Tf:

,00,000,0004,01,02,039,04,043,052,056,...,yakni,yang,yerusalem,yesus,yogyakarta,yunani,yusuf,zat,ziarah,zoetry
0,1,0,0,1,1,0,0,0,1,0,...,1,15,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,7,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,14,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,9,0,0,0,0,0,0,0,0
4,0,0,0,1,2,1,0,2,0,1,...,0,3,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,10,0,0,0,0,0,0,0,0
6,0,0,0,1,1,0,0,0,0,0,...,0,8,0,0,1,0,1,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,11,0,0,0,0,0,0,0,0
8,2,1,0,0,0,0,0,0,0,0,...,0,4,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,5,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,6,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,4,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,5,0,0,0,0,0,0,0,0
13,0,1,0,0,0,0,0,0,0,0,...,0,9,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,12,1,5,0,0,0,0,5,0
15,0,0,0,0,0,0,0,0,0,0,...,0,8,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,1,0,0,0,...,0,2,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,5,0,0,0,0,0,0,0,0
18,1,0,0,0,0,0,0,0,0,0,...,0,2,0,0,1,0,0,0,0,0
19,0,1,0,0,0,0,0,0,0,0,...,0,5,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,6,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,7,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,1,7,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,4,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,6,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,11,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,4,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,5,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,7,0,0,0,0,0,0,0,0
29,0,3,0,0,0,0,0,0,0,0,...,0,15,0,0,0,0,0,2,0,0
30,0,0,1,0,0,0,0,0,0,0,...,0,7,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,...,1,4,0,0,0,0,0,0,0,1
32,0,0,0,0,0,0,0,0,0,0,...,0,18,0,0,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,...,1,10,0,0,0,0,0,0,0,0
34,0,0,0,0,0,0,0,0,0,0,...,0,17,0,0,0,0,0,0,0,0
35,0,0,0,0,0,0,0,0,0,0,...,0,7,0,0,0,0,0,0,0,0
36,0,0,0,0,0,0,0,0,0,0,...,0,8,0,0,0,0,0,0,0,0
37,0,0,0,0,0,0,0,0,0,0,...,0,5,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,...,0,26,0,0,0,0,0,0,0,0
39,0,0,0,0,0,0,0,0,0,0,...,0,13,0,0,0,8,0,0,0,0

In [31]:
print("Matriks Tf (Khusus data train:)")
tf_train = tf_matrix[:n_train]
tf_train.shape

Matriks Tf (Khusus data train:)

(30, 3005)

In [32]:
# Penyesuain df agar query(data set) tidak dihitung pada perhitungan df
transformer = TfidfTransformer(sublinear_tf=True)
n = n_train
df = tf_train.astype(bool).sum(axis=0)
idf = np.log(n/df)
transformer.idf_ = idf

weight = transformer.fit_transform(tf)
print(f"Jumlah Dokumen: {weight.shape[0]}")
print(f"Jumlah Term: {weight.shape[1]}")

Jumlah Dokumen: 40
Jumlah Term: 3005

In [33]:
weight_matrix = pd.DataFrame(weight.toarray(), columns=vectorizer.get_feature_names_out())
weight_matrix

,00,000,0004,01,02,039,04,043,052,056,...,yakni,yang,yerusalem,yesus,yogyakarta,yunani,yusuf,zat,ziarah,zoetry
0,0.050268,0.000000,0.000000,0.050268,0.050268,0.000000,0.000000,0.000000,0.060739,0.000000,...,0.044142,0.056020,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.065951,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.048344,0.060211,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.052630,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
4,0.000000,0.000000,0.000000,0.054773,0.092739,0.066184,0.000000,0.112059,0.000000,0.066184,...,0.000000,0.034547,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.065115,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
6,0.000000,0.000000,0.000000,0.060247,0.060247,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.055759,0.000000,0.00000,0.065456,0.000000,0.072798,0.000000,0.00000,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.063048,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
8,0.109944,0.060580,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.046571,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.043475,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.082978,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.049864,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.059611,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
13,0.000000,0.051677,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.053227,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.056291,0.064941,0.16946,0.000000,0.000000,0.000000,0.000000,0.16946,0.000000
15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.057045,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.090792,0.000000,0.000000,0.000000,...,0.000000,0.038236,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.059080,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
18,0.077883,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.039632,0.000000,0.00000,0.084617,0.000000,0.000000,0.000000,0.00000,0.000000
19,0.000000,0.051945,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.043667,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.059241,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.047316,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.044919,0.045290,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.047128,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
24,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.063443,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.064108,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
26,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.044264,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
27,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.066769,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
28,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.052253,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
29,0.000000,0.077848,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.044312,0.000000,0.00000,0.000000,0.000000,0.000000,0.081347,0.00000,0.000000
30,0.000000,0.000000,0.068662,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.050311,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.056684,0.046295,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.077997
32,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.056454,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
33,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.046756,0.052849,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
34,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.047625,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
35,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.061757,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
36,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.058192,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
37,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.055865,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
38,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.046913,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.064754,0.000000,0.00000,0.000000,0.224883,0.000000,0.000000,0.00000,0.000000

In [34]:
# Pembagian matriks bobot
weight_train = weight_matrix[:n_train]
weight_test = weight_matrix[n_train:]

If **file code & images** cannot be accessed, you can use the repository link which can be accessed by using [this link!](https://colab.research.google.com/drive/1Te6z5clvOH31d2NwWRjT4HeUgiUwFI89?usp=sharing "link Google Colab")

## THANK YOU😸

<img src="https://i.pinimg.com/originals/47/20/51/472051c6d88bd2837525520597251d67.gif" alt="Footer Background">